### ISSUE TITLE
Crash on dedicated Sever

### ISSUE THREAD

**Issue by LukaPix** [e99999/GT-Classic#111]
Your Mod crashes trying to add the recipe for the magic energy converter
[latest.log](https://github.com/e99999/GT-Classic/files/3882430/latest.log)

**Comment by Muramasa-** [comment]
https://github.com/e99999/GT-Classic/blob/ec01930a0bf7537068c9012ad8c53e02dd543034/src/main/java/gtclassic/common/tile/GTTileMagicEnergyConverter.java#L401

Just need to check if the size is more than 0, rather then getting element 0 and null checking.

**Comment by e99999** [comment]
ok should be fixed for real now thanks for making the report. I think whats happening is the fluid is validated when using the method i wrote for adding modded fluids to the recipe list,
but since GT Classic does not generate all possible filled fluid containers by default, you can still null the actual fluid container input for the recipe list.

**Comment by LukaPix** [comment]
How can one compile your mod, it runs into errors trying to compile it with ic2c gradlew
Or, when can one expect the release to push this fix ?

**Comment by Trinsdar** [comment]
There will probably be a release next week

**Comment by e99999** [comment]
yeah shooting for monday as trins said

**Comment by e99999** [comment]
also @LukaPix if you are unable to play until the update, try enabling "displayAllFluidTubes" in the GTC Config, that might fix things temporarily until i can get the patch out
