### ISSUE TITLE
Breaks Oil Generation in Pneumaticcraft-Repressurized

### ISSUE THREAD

**Issue by AbieTheFishman** [e99999/GT-Classic#133]
This breaks or turns off the Oil Generation in Pneumaticcraft-Repressurized
- pneumaticcraft-repressurized-1.12.2-0.11.14-395

It changes the config setting in Pneumaticcraft for oil generation to 0 (default is 15)

        # Chance per chunk in percentage to generate an Oil Lake. Set to 0 for no spawns
        # Min: 0.0
        # Max: 100.0
        D:oilGenerationChance=0

**Comment by Speiger** [comment]
@AbieTheFishman eh this mod does not have a single line of code that interacts with Pneumaticcraft,
Configfiles are handled by Forge, and I know for a fact he is not even capable of doing this.

Why is this issue even a thing.

**Comment by e99999** [comment]
@AbieTheFishman Do you have proof of this or just guessing? GTC makes no reference to oil generation or pneumatic-craft re-pressurized anywhere in the entire mod. Would be happy to fix it if is indeed my issue 🤷‍♂️

**Comment by Rongmario** [comment]
Issue:
https://github.com/TeamPneumatic/pnc-repressurized/blob/d09bfac6b57bbac1647503a27a60db933b83293b/src/main/java/me/desht/pneumaticcraft/common/worldgen/WorldGeneratorPneumaticCraft.java#L33

Tell PneumaticCraft author to use his own oil's block.

**Comment by e99999** [comment]
closed because it has nothing todo with GTC, good catch @Rongmario

**Comment by AbieTheFishman** [comment]
These are the mods I have installed.

When GregTech Classic is enabled - no Oil is generated and the the P-R config file is changed as mentioned above.

Gravisuit Classic	trinsdar	gravisuit-1.0.8.2.jar	
**GregTech Classic	e99999	GTClassic-1.1.4.jar.disabled	
IC2 Classic	sfPlayer1	IC2Classic 1.12-1.5.4.5.jar	
IC2C Addons	MedurisDev	ic2caddons-1.0.2.jar	
IC2C Extras	trinsdar	IC2CExtras-1.4.4.12.jar	
JourneyMap	techbrew	journeymap-1.12.2-5.7.1.jar	
Just Enough Items (JEI)	mezz	jei_1.12.2-4.15.0.291.jar	
PneumaticCraft: Repressurized	desht_08	pneumaticcraft-repressurized-1.12.2-0.11.14-395.jar	
The One Probe	McJty	theoneprobe-1.12-1.4.28.jar	
TOP Addons	DrManganese	topaddons-1.12.2-1.13.0.jar	
World Stripper	EwyBoy	World-Stripper-1.6.0-1.12.2.jar

I'll report to the P-R site.

Thank you gentlemen for your quick responsiveness.

**Comment by desht** [comment]
This is neither a problem in GTC nor PNC.  PNC will switch off its own oil generation if it discovers another mod has already registered the "oil" fluid (and there's no associated block).  In this case, it will accept GTC's Oil in the refinery, so I don't see what the problem is.

> Tell PneumaticCraft author to use his own oil's block.

No.

**Comment by Rongmario** [comment]
> No. 

So its obviously not intended, and you're going to close the issues after coming up with an excuse? Watch your tone young lad.

**Comment by desht** [comment]
1. It's not an excuse.  It's correct behaviour, as I've already clearly explained, and I have zero intention of changing it. 
2. I'm neither young, nor do I particularly appreciate being spoken to in this way.

**Comment by Rongmario** [comment]
You've not explained it that way in the original issue thread, and I couldn't care less on how you wanted to be talked to.

**Comment by desht** [comment]
Doesn't matter.  I will not be commenting further.  Neither GTC nor PNC are broken by this (unless someone can actually demonstrate otherwise), and your suggestion that I use my own fluid name (which would break a ton of existing worlds) is non-viable.

We're done here.

**Comment by Rongmario** [comment]
Good on you mate, just don't go back on your words in the future; it's for your own good.

**Comment by e99999** [comment]
If I could double close this issue I would, has nothing to do with GTC just a bad attempt at compat by Pneumatic Craft.

**Comment by AbieTheFishman** [comment]
Please do - I'd like to share that desht did suggest a reasonable work around for my purposes. 
[https://github.com/TeamPneumatic/pnc-repressurized/issues/452#issuecomment-619386583]

Thanks again. And I apologize for my clumsiness and any unnecessary drama I may have caused.

**Comment by e99999** [comment]
Actually I take that back, its worth noting what i found @desht 

when you overwrite a fluid you do not overwrite the block association. I found this out when I added brine in gtc a while ago without a fluid block - you could place Mekanism brine blocks using MY fluid. 

So in your check for a fluid block, you find MY oil but YOUR fluid block associated with it because GTC has no fluid block. so if anyone from any mods adds an "oil" fluid your mod block is automatically associated - which will ALWAYS return not null in your check.

**Comment by desht** [comment]
No, that's not really the case.  I've been through this before with other mods (BuildCraft and Immersive Petroleum), so I have a fairly good idea how it functions.

When PneumaticCraft registers its fluids, I check if a fluid has already been registered by that name.  If one has been, I do *not* overwrite the fluid, and I do *not* register a block for that fluid.  Instead, I log a warning that a fluid has already been found, and continue.

So in the case where GTC loads first and registers "oil" with no block, I don't add a block. Which is exactly why PNC oil lake worldgen is then disabled, as the OP reported.  You call that "a bad attempt at compat", but as far as I'm concerned, it's the most reasonable course of action given a bad system (i.e. no namespaced fluids in 1.12.2).  If you have a better proposal, then by all means make a suggestion.  But I won't be renaming the "oil" fluid in PNC.

**Comment by Speiger** [comment]
@desht no mod is required to add a Block to a Fluid, the only reason fluid compat exists to reduce duplicated fluids. FluidBlocks on the other hand they can exist as many as they want. You can choose to do it your way but @e99999 can to do the same as he did. That your mod makes itself unplayable in some regards because you do not acknowledge that other ways exist is the problem.
In other words. If you dont find a fluid block present with the fluid then you can do 1 simple thing,
register your block with the new fluid you found that matches yours. It keeps your mod not broken and makes you a better coder in that regard

**Comment by desht** [comment]
??? I have blamed no one.  I've said repeatedly that neither mod is doing anything wrong.  PNC:R does not in any way "make itself unplayable"; it simply switches off its own worldgen, because the fluid it needs for the Refinery ("oil") is available via another mod (in this case, GTC, but it could also be BuildCraft, or Immersive Petroleum...)

Having said, registering a PNC:R "pneumaticcraft:oil" block with your fluid is a good idea (although TBH it's unlikely to be happen now; I'd need to do a lot of testing, PNC:R is pretty much in maintenance mode for 1.12.2, and there's already a good solution - the modpack author chooses which oil takes precedence, by setting the mod load order).

But I have a BIG problem with this concept that I'm blaming anyone *at all*, or that I've somehow broken either mod or made a "mistake", because I am not, and I have not.  I deliberately chose to do it the way I do, and if you don't like that, that's your prerogative.  But don't go accusing me of mistakes, or bad coding.
